name: VKIS GALLERY

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up nodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean and Install dependencies
        run: |
          npm install
          rm -rf node_modules package-lock.json
      
      - name: Create .env
        run: |
          echo 'VITE_VKIS_API_URL=${{ secrets.VITE_VKIS_API_URL}}' >> .env
          echo 'VITE_VKIS_RAPID_API_KEY=${{ secrets.VITE_VKIS_RAPID_API_KEY}}' >> .env
          echo 'VITE_VKIS_API_KEY=${{ secrets.VITE_VKIS_API_KEY}}' >> .env

      - name: Build Vkis App
        run: npm run build